services:
  token-generator:
    build: https://github.com/schufi73/TokenGenerator.git#master
    ports:
      - "8444:8444"
    volumes:
      - db-data:/app/db
    restart: always

volumes:
  db-data:
