events {}

http {
    server {
        listen 8443 ssl;
        server_name prtg.nsource.ch;

        ssl_certificate     /etc/letsencrypt/live/prtg.nsource.ch/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/prtg.nsource.ch/privkey.pem;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://token-generator:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
